/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const HealthMetric = IDL.Record({
  'bodyWeightLbs' : IDL.Opt(IDL.Float64),
  'heartRateBpm' : IDL.Opt(IDL.Nat),
  'stepsCount' : IDL.Opt(IDL.Nat),
  'timestamp' : Time,
  'bloodPressureDiastolic' : IDL.Opt(IDL.Nat),
  'caloriesBurned' : IDL.Opt(IDL.Nat),
  'bloodPressureSystolic' : IDL.Opt(IDL.Nat),
});
export const CompletedExercise = IDL.Record({
  'date' : Time,
  'exerciseName' : IDL.Text,
});
export const DailyWorkoutCompletion = IDL.Record({
  'date' : Time,
  'completed' : IDL.Bool,
  'workoutName' : IDL.Text,
});
export const LoggedSet = IDL.Record({
  'weightLbs' : IDL.Float64,
  'actualReps' : IDL.Nat,
  'timestamp' : Time,
  'exerciseName' : IDL.Text,
});
export const FitnessProfile = IDL.Record({
  'totalWorkoutsCompleted' : IDL.Nat,
  'workoutStreak' : IDL.Nat,
});
export const MemberData = IDL.Record({
  'healthMetrics' : IDL.Vec(HealthMetric),
  'completedExercises' : IDL.Vec(CompletedExercise),
  'workoutCompletions' : IDL.Vec(DailyWorkoutCompletion),
  'loggedSets' : IDL.Vec(LoggedSet),
  'profile' : FitnessProfile,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'fitnessGoal' : IDL.Text,
  'name' : IDL.Text,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const MuscleGroup = IDL.Variant({
  'shoulders' : IDL.Null,
  'arms' : IDL.Null,
  'back' : IDL.Null,
  'core' : IDL.Null,
  'chest' : IDL.Null,
  'legs' : IDL.Null,
  'cardio' : IDL.Null,
});
export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'instructions' : IDL.Text,
  'muscleGroups' : IDL.Vec(MuscleGroup),
  'videoUrl' : IDL.Text,
  'restTimeSeconds' : IDL.Nat,
});
export const ExerciseDay = IDL.Record({
  'exercises' : IDL.Vec(Exercise),
  'dayName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminGetUserData' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(MemberData)],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHealthMetricsHistory' : IDL.Func([], [IDL.Vec(HealthMetric)], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getLatestHealthMetric' : IDL.Func([], [IDL.Opt(HealthMetric)], ['query']),
  'getLoggedSets' : IDL.Func([], [IDL.Vec(LoggedSet)], ['query']),
  'getPersonalProfile' : IDL.Func([], [IDL.Opt(FitnessProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkoutHistory' : IDL.Func(
      [],
      [IDL.Vec(DailyWorkoutCompletion)],
      ['query'],
    ),
  'getWorkoutRoutine' : IDL.Func([], [IDL.Vec(ExerciseDay)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logExerciseSet' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [], []),
  'logHealthMetric' : IDL.Func([HealthMetric], [], []),
  'markExerciseCompleted' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'trackWorkoutCompletion' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const HealthMetric = IDL.Record({
    'bodyWeightLbs' : IDL.Opt(IDL.Float64),
    'heartRateBpm' : IDL.Opt(IDL.Nat),
    'stepsCount' : IDL.Opt(IDL.Nat),
    'timestamp' : Time,
    'bloodPressureDiastolic' : IDL.Opt(IDL.Nat),
    'caloriesBurned' : IDL.Opt(IDL.Nat),
    'bloodPressureSystolic' : IDL.Opt(IDL.Nat),
  });
  const CompletedExercise = IDL.Record({
    'date' : Time,
    'exerciseName' : IDL.Text,
  });
  const DailyWorkoutCompletion = IDL.Record({
    'date' : Time,
    'completed' : IDL.Bool,
    'workoutName' : IDL.Text,
  });
  const LoggedSet = IDL.Record({
    'weightLbs' : IDL.Float64,
    'actualReps' : IDL.Nat,
    'timestamp' : Time,
    'exerciseName' : IDL.Text,
  });
  const FitnessProfile = IDL.Record({
    'totalWorkoutsCompleted' : IDL.Nat,
    'workoutStreak' : IDL.Nat,
  });
  const MemberData = IDL.Record({
    'healthMetrics' : IDL.Vec(HealthMetric),
    'completedExercises' : IDL.Vec(CompletedExercise),
    'workoutCompletions' : IDL.Vec(DailyWorkoutCompletion),
    'loggedSets' : IDL.Vec(LoggedSet),
    'profile' : FitnessProfile,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'fitnessGoal' : IDL.Text,
    'name' : IDL.Text,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const MuscleGroup = IDL.Variant({
    'shoulders' : IDL.Null,
    'arms' : IDL.Null,
    'back' : IDL.Null,
    'core' : IDL.Null,
    'chest' : IDL.Null,
    'legs' : IDL.Null,
    'cardio' : IDL.Null,
  });
  const Exercise = IDL.Record({
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'instructions' : IDL.Text,
    'muscleGroups' : IDL.Vec(MuscleGroup),
    'videoUrl' : IDL.Text,
    'restTimeSeconds' : IDL.Nat,
  });
  const ExerciseDay = IDL.Record({
    'exercises' : IDL.Vec(Exercise),
    'dayName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminGetUserData' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(MemberData)],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHealthMetricsHistory' : IDL.Func(
        [],
        [IDL.Vec(HealthMetric)],
        ['query'],
      ),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getLatestHealthMetric' : IDL.Func([], [IDL.Opt(HealthMetric)], ['query']),
    'getLoggedSets' : IDL.Func([], [IDL.Vec(LoggedSet)], ['query']),
    'getPersonalProfile' : IDL.Func([], [IDL.Opt(FitnessProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkoutHistory' : IDL.Func(
        [],
        [IDL.Vec(DailyWorkoutCompletion)],
        ['query'],
      ),
    'getWorkoutRoutine' : IDL.Func([], [IDL.Vec(ExerciseDay)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logExerciseSet' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [], []),
    'logHealthMetric' : IDL.Func([HealthMetric], [], []),
    'markExerciseCompleted' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'trackWorkoutCompletion' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };