/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompletedExercise { 'date' : Time, 'exerciseName' : string }
export interface DailyWorkoutCompletion {
  'date' : Time,
  'completed' : boolean,
  'workoutName' : string,
}
export interface Exercise {
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
  'instructions' : string,
  'muscleGroups' : Array<MuscleGroup>,
  'videoUrl' : string,
  'restTimeSeconds' : bigint,
}
export interface ExerciseDay {
  'exercises' : Array<Exercise>,
  'dayName' : string,
}
export interface FitnessProfile {
  'totalWorkoutsCompleted' : bigint,
  'workoutStreak' : bigint,
}
export interface HealthMetric {
  'bodyWeightLbs' : [] | [number],
  'heartRateBpm' : [] | [bigint],
  'stepsCount' : [] | [bigint],
  'timestamp' : Time,
  'bloodPressureDiastolic' : [] | [bigint],
  'caloriesBurned' : [] | [bigint],
  'bloodPressureSystolic' : [] | [bigint],
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface LoggedSet {
  'weightLbs' : number,
  'actualReps' : bigint,
  'timestamp' : Time,
  'exerciseName' : string,
}
export interface MemberData {
  'healthMetrics' : Array<HealthMetric>,
  'completedExercises' : Array<CompletedExercise>,
  'workoutCompletions' : Array<DailyWorkoutCompletion>,
  'loggedSets' : Array<LoggedSet>,
  'profile' : FitnessProfile,
}
export type MuscleGroup = { 'shoulders' : null } |
  { 'arms' : null } |
  { 'back' : null } |
  { 'core' : null } |
  { 'chest' : null } |
  { 'legs' : null } |
  { 'cardio' : null };
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type Time = bigint;
export interface UserProfile { 'fitnessGoal' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminGetUserData' : ActorMethod<[Principal], [] | [MemberData]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHealthMetricsHistory' : ActorMethod<[], Array<HealthMetric>>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getLatestHealthMetric' : ActorMethod<[], [] | [HealthMetric]>,
  'getLoggedSets' : ActorMethod<[], Array<LoggedSet>>,
  'getPersonalProfile' : ActorMethod<[], [] | [FitnessProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkoutHistory' : ActorMethod<[], Array<DailyWorkoutCompletion>>,
  'getWorkoutRoutine' : ActorMethod<[], Array<ExerciseDay>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logExerciseSet' : ActorMethod<[string, bigint, number], undefined>,
  'logHealthMetric' : ActorMethod<[HealthMetric], undefined>,
  'markExerciseCompleted' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'trackWorkoutCompletion' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];