/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    name: string;
    reps: bigint;
    sets: bigint;
    instructions: string;
    muscleGroups: Array<MuscleGroup>;
    videoUrl: string;
    restTimeSeconds: bigint;
}
export interface CompletedExercise {
    date: Time;
    exerciseName: string;
}
export interface UserProfile {
    fitnessGoal: string;
    name: string;
}
export type Time = bigint;
export interface HealthMetric {
    bodyWeightLbs?: number;
    heartRateBpm?: bigint;
    stepsCount?: bigint;
    timestamp: Time;
    bloodPressureDiastolic?: bigint;
    caloriesBurned?: bigint;
    bloodPressureSystolic?: bigint;
}
export interface ExerciseDay {
    exercises: Array<Exercise>;
    dayName: string;
}
export interface InviteCode {
    created: Time;
    code: string;
    used: boolean;
}
export interface RSVP {
    name: string;
    inviteCode: string;
    timestamp: Time;
    attending: boolean;
}
export interface DailyWorkoutCompletion {
    date: Time;
    completed: boolean;
    workoutName: string;
}
export interface MemberData {
    healthMetrics: Array<HealthMetric>;
    completedExercises: Array<CompletedExercise>;
    workoutCompletions: Array<DailyWorkoutCompletion>;
    loggedSets: Array<LoggedSet>;
    profile: FitnessProfile;
}
export interface LoggedSet {
    weightLbs: number;
    actualReps: bigint;
    timestamp: Time;
    exerciseName: string;
}
export interface FitnessProfile {
    totalWorkoutsCompleted: bigint;
    workoutStreak: bigint;
}
export enum MuscleGroup {
    shoulders = "shoulders",
    arms = "arms",
    back = "back",
    core = "core",
    chest = "chest",
    legs = "legs",
    cardio = "cardio"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminGetUserData(user: Principal): Promise<MemberData | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    generateInviteCode(): Promise<string>;
    getAllRSVPs(): Promise<Array<RSVP>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getHealthMetricsHistory(): Promise<Array<HealthMetric>>;
    getInviteCodes(): Promise<Array<InviteCode>>;
    getLatestHealthMetric(): Promise<HealthMetric | null>;
    getLoggedSets(): Promise<Array<LoggedSet>>;
    getPersonalProfile(): Promise<FitnessProfile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkoutHistory(): Promise<Array<DailyWorkoutCompletion>>;
    getWorkoutRoutine(): Promise<Array<ExerciseDay>>;
    isCallerAdmin(): Promise<boolean>;
    logExerciseSet(exerciseName: string, reps: bigint, weight: number): Promise<void>;
    logHealthMetric(metric: HealthMetric): Promise<void>;
    markExerciseCompleted(exerciseName: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitRSVP(name: string, attending: boolean, inviteCode: string): Promise<void>;
    trackWorkoutCompletion(workoutName: string): Promise<void>;
}
import type { CompletedExercise as _CompletedExercise, DailyWorkoutCompletion as _DailyWorkoutCompletion, Exercise as _Exercise, ExerciseDay as _ExerciseDay, FitnessProfile as _FitnessProfile, HealthMetric as _HealthMetric, LoggedSet as _LoggedSet, MemberData as _MemberData, MuscleGroup as _MuscleGroup, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminGetUserData(arg0: Principal): Promise<MemberData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserData(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserData(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHealthMetricsHistory(): Promise<Array<HealthMetric>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthMetricsHistory();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthMetricsHistory();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodes();
            return result;
        }
    }
    async getLatestHealthMetric(): Promise<HealthMetric | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestHealthMetric();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestHealthMetric();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoggedSets(): Promise<Array<LoggedSet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoggedSets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoggedSets();
            return result;
        }
    }
    async getPersonalProfile(): Promise<FitnessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersonalProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersonalProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutHistory(): Promise<Array<DailyWorkoutCompletion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutHistory();
            return result;
        }
    }
    async getWorkoutRoutine(): Promise<Array<ExerciseDay>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutRoutine();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutRoutine();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logExerciseSet(arg0: string, arg1: bigint, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logExerciseSet(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logExerciseSet(arg0, arg1, arg2);
            return result;
        }
    }
    async logHealthMetric(arg0: HealthMetric): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logHealthMetric(to_candid_HealthMetric_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logHealthMetric(to_candid_HealthMetric_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async markExerciseCompleted(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markExerciseCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markExerciseCompleted(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2);
            return result;
        }
    }
    async trackWorkoutCompletion(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackWorkoutCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackWorkoutCompletion(arg0);
            return result;
        }
    }
}
function from_candid_ExerciseDay_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExerciseDay): ExerciseDay {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Exercise_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exercise): Exercise {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_HealthMetric_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthMetric): HealthMetric {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_MemberData_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberData): MemberData {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_MuscleGroup_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MuscleGroup): MuscleGroup {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MemberData]): MemberData | null {
    return value.length === 0 ? null : from_candid_MemberData_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HealthMetric]): HealthMetric | null {
    return value.length === 0 ? null : from_candid_HealthMetric_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FitnessProfile]): FitnessProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exercises: Array<_Exercise>;
    dayName: string;
}): {
    exercises: Array<Exercise>;
    dayName: string;
} {
    return {
        exercises: from_candid_vec_n19(_uploadFile, _downloadFile, value.exercises),
        dayName: value.dayName
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    reps: bigint;
    sets: bigint;
    instructions: string;
    muscleGroups: Array<_MuscleGroup>;
    videoUrl: string;
    restTimeSeconds: bigint;
}): {
    name: string;
    reps: bigint;
    sets: bigint;
    instructions: string;
    muscleGroups: Array<MuscleGroup>;
    videoUrl: string;
    restTimeSeconds: bigint;
} {
    return {
        name: value.name,
        reps: value.reps,
        sets: value.sets,
        instructions: value.instructions,
        muscleGroups: from_candid_vec_n22(_uploadFile, _downloadFile, value.muscleGroups),
        videoUrl: value.videoUrl,
        restTimeSeconds: value.restTimeSeconds
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    healthMetrics: Array<_HealthMetric>;
    completedExercises: Array<_CompletedExercise>;
    workoutCompletions: Array<_DailyWorkoutCompletion>;
    loggedSets: Array<_LoggedSet>;
    profile: _FitnessProfile;
}): {
    healthMetrics: Array<HealthMetric>;
    completedExercises: Array<CompletedExercise>;
    workoutCompletions: Array<DailyWorkoutCompletion>;
    loggedSets: Array<LoggedSet>;
    profile: FitnessProfile;
} {
    return {
        healthMetrics: from_candid_vec_n4(_uploadFile, _downloadFile, value.healthMetrics),
        completedExercises: value.completedExercises,
        workoutCompletions: value.workoutCompletions,
        loggedSets: value.loggedSets,
        profile: value.profile
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bodyWeightLbs: [] | [number];
    heartRateBpm: [] | [bigint];
    stepsCount: [] | [bigint];
    timestamp: _Time;
    bloodPressureDiastolic: [] | [bigint];
    caloriesBurned: [] | [bigint];
    bloodPressureSystolic: [] | [bigint];
}): {
    bodyWeightLbs?: number;
    heartRateBpm?: bigint;
    stepsCount?: bigint;
    timestamp: Time;
    bloodPressureDiastolic?: bigint;
    caloriesBurned?: bigint;
    bloodPressureSystolic?: bigint;
} {
    return {
        bodyWeightLbs: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.bodyWeightLbs)),
        heartRateBpm: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.heartRateBpm)),
        stepsCount: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.stepsCount)),
        timestamp: value.timestamp,
        bloodPressureDiastolic: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.bloodPressureDiastolic)),
        caloriesBurned: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.caloriesBurned)),
        bloodPressureSystolic: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.bloodPressureSystolic))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shoulders: null;
} | {
    arms: null;
} | {
    back: null;
} | {
    core: null;
} | {
    chest: null;
} | {
    legs: null;
} | {
    cardio: null;
}): MuscleGroup {
    return "shoulders" in value ? MuscleGroup.shoulders : "arms" in value ? MuscleGroup.arms : "back" in value ? MuscleGroup.back : "core" in value ? MuscleGroup.core : "chest" in value ? MuscleGroup.chest : "legs" in value ? MuscleGroup.legs : "cardio" in value ? MuscleGroup.cardio : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExerciseDay>): Array<ExerciseDay> {
    return value.map((x)=>from_candid_ExerciseDay_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exercise>): Array<Exercise> {
    return value.map((x)=>from_candid_Exercise_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MuscleGroup>): Array<MuscleGroup> {
    return value.map((x)=>from_candid_MuscleGroup_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HealthMetric>): Array<HealthMetric> {
    return value.map((x)=>from_candid_HealthMetric_n5(_uploadFile, _downloadFile, x));
}
function to_candid_HealthMetric_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HealthMetric): _HealthMetric {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bodyWeightLbs?: number;
    heartRateBpm?: bigint;
    stepsCount?: bigint;
    timestamp: Time;
    bloodPressureDiastolic?: bigint;
    caloriesBurned?: bigint;
    bloodPressureSystolic?: bigint;
}): {
    bodyWeightLbs: [] | [number];
    heartRateBpm: [] | [bigint];
    stepsCount: [] | [bigint];
    timestamp: _Time;
    bloodPressureDiastolic: [] | [bigint];
    caloriesBurned: [] | [bigint];
    bloodPressureSystolic: [] | [bigint];
} {
    return {
        bodyWeightLbs: value.bodyWeightLbs ? candid_some(value.bodyWeightLbs) : candid_none(),
        heartRateBpm: value.heartRateBpm ? candid_some(value.heartRateBpm) : candid_none(),
        stepsCount: value.stepsCount ? candid_some(value.stepsCount) : candid_none(),
        timestamp: value.timestamp,
        bloodPressureDiastolic: value.bloodPressureDiastolic ? candid_some(value.bloodPressureDiastolic) : candid_none(),
        caloriesBurned: value.caloriesBurned ? candid_some(value.caloriesBurned) : candid_none(),
        bloodPressureSystolic: value.bloodPressureSystolic ? candid_some(value.bloodPressureSystolic) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
